all: dong/dong_list.txt pokegif/pokegif_list.txt

dong/dong_list.txt:
	ls dong > dong_list.txt
	mv dong_list.txt dong/
pokegif/pokegif_list.txt:
	ls pokegif > pokegif_list.txt
	mv pokegif_list.txt pokegif/

clean:
	rm dong/dong_list.txt
	rm pokegif/pokegif_list.txt
